#![forbid(unsafe_code)]

//! Piteka HTTP API — first-slice endpoints for action requests and approvals.
//!
//! This crate implements the REST surface described in Master Plan §59 D-07.
//! It exposes stable JSON error shapes, idempotent mutations via `Idempotency-Key`,
//! and an OpenAPI contract checked in CI.
//!
//! # Endpoints
//!
//! | Method | Path | Description |
//! |--------|------|-------------|
//! | `GET`  | `/api/v1/action-requests` | List all action requests |
//! | `GET`  | `/api/v1/action-requests/{id}` | Get a single action request |
//! | `POST` | `/api/v1/action-requests` | Propose a new action request |
//! | `POST` | `/api/v1/action-requests/{id}/approve` | Approve an action request |
//! | `POST` | `/api/v1/action-requests/{id}/reject` | Reject an action request |
//! | `POST` | `/api/v1/action-requests/{id}/revoke` | Revoke an approved request |
//!
//! # Idempotency
//!
//! The `propose`, `approve`, `reject`, and `revoke` endpoints honour the
//! `Idempotency-Key` header. When present, a second call with the same key
//! returns the original result without re-executing the mutation.
//!
//! # OpenAPI
//!
//! The contract lives in `openapi/openapi.yaml` and is checked in CI.
//! The schema is derived from the request/response types in this crate.

pub mod error;
pub mod handlers;
pub mod models;
pub mod routes;

pub use error::{ApiError, ErrorResponse};
pub use models::{
    ActionRequestResponse, ActionRequestSummary, ApproveRequest, CreateActionRequestRequest,
    RejectRequest, RevokeRequest,
};

use axum::{extract::Request, middleware::Next, response::IntoResponse};
use piteka_application::ActionRequestUseCase;
use piteka_storage::{
    ActionRequestStore, ApprovalDecisionStore, AuditLog,
};
use crate::error::{ErrorCause, ErrorDetail};

/// OpenAPI schema for the first-slice API (checked in at `openapi/openapi.yaml`).
///
/// The schema is maintained as a YAML file and regenerated by
/// `scripts/regenerate_openapi.sh` when source types change.
pub const OPENAPI_SPEC: &str = include_str!("../../../openapi/openapi.yaml");

/// Middleware that extracts tenant from the `X-Tenant-Id` header.
///
/// Fails closed when the header is missing.
#[allow(dead_code)]
async fn require_tenant(req: Request, next: Next) -> axum::response::Response {
    let tenant_id = req
        .headers()
        .get("X-Tenant-Id")
        .and_then(|v| v.to_str().ok())
        .map(|s| s.to_string());

    match tenant_id {
        Some(_id) => {
            let mut req = req;
            req.extensions_mut().insert(_id);
            next.run(req).await
        }
        None => (
            axum::http::StatusCode::BAD_REQUEST,
            axum::response::Json(ErrorResponse {
                error: ErrorDetail {
                    code: "MISSING_REQUIRED_HEADER".to_string(),
                    message: "The `X-Tenant-Id` header is required".to_string(),
                    causes: Some(vec![ErrorCause {
                        code: "MISSING_REQUIRED_HEADER".to_string(),
                        message: "The `X-Tenant-Id` header must be present".to_string(),
                        source: Some("X-Tenant-Id".to_string()),
                    }]),
                },
            }),
        )
            .into_response(),
    }
}

/// A minimal in-memory port implementation for testing.
#[derive(Clone)]
pub struct TestPorts {
    pub request_store: std::sync::Arc<piteka_storage::memory::InMemoryActionRequestStore>,
    pub decision_store: std::sync::Arc<piteka_storage::memory::InMemoryApprovalDecisionStore>,
    pub audit_log: std::sync::Arc<piteka_storage::memory::InMemoryAuditLog>,
}

impl TestPorts {
    pub fn new() -> Self {
        Self {
            request_store: std::sync::Arc::new(piteka_storage::memory::InMemoryActionRequestStore::default()),
            decision_store: std::sync::Arc::new(piteka_storage::memory::InMemoryApprovalDecisionStore::default()),
            audit_log: std::sync::Arc::new(piteka_storage::memory::InMemoryAuditLog::default()),
        }
    }

    pub fn use_case(&self) -> ActionRequestUseCase<TestPorts> {
        ActionRequestUseCase::new(self.clone())
    }
}

impl piteka_application::ActionRequestPorts for TestPorts {
    fn request_store(&self) -> &dyn ActionRequestStore {
        &self.request_store
    }

    fn decision_store(&self) -> &dyn ApprovalDecisionStore {
        &self.decision_store
    }

    fn audit_log(&self) -> &dyn AuditLog {
        &self.audit_log
    }

    fn clock(&self) -> &dyn piteka_application::Clock {
        // Return a static clock for testing purposes.
        // In production, this would return a reference to a real clock.
        static CLOCK: std::sync::OnceLock<TestClock> = std::sync::OnceLock::new();
        CLOCK.get_or_init(TestClock::default)
    }
}

impl Default for TestPorts {
    fn default() -> Self {
        Self::new()
    }
}

/// A deterministic clock that steps forward by 1 second per call.
#[derive(Default)]
struct TestClock {
    now: std::sync::Arc<std::sync::atomic::AtomicU64>,
}

impl TestClock {
    #[allow(dead_code)]
    fn at(second: u64) -> Self {
        Self {
            now: std::sync::Arc::new(std::sync::atomic::AtomicU64::new(second)),
        }
    }
}

impl piteka_application::Clock for TestClock {
    fn unix_seconds(&self) -> u64 {
        self.now.fetch_add(1, std::sync::atomic::Ordering::SeqCst)
    }
}

#[cfg(test)]
mod tests;
