#![forbid(unsafe_code)]

//! Piteka HTTP API — first-slice endpoints for action requests and approvals.
//!
//! This crate implements the REST surface described in Master Plan §59 D-07.
//! It exposes stable JSON error shapes, idempotent mutations via `Idempotency-Key`,
//! and an OpenAPI contract checked in CI.
//!
//! # Endpoints
//!
//! | Method | Path | Description |
//! |--------|------|-------------|
//! | `GET`  | `/api/v1/action-requests` | List all action requests |
//! | `GET`  | `/api/v1/action-requests/{id}` | Get a single action request |
//! | `POST` | `/api/v1/action-requests` | Propose a new action request |
//! | `POST` | `/api/v1/action-requests/{id}/approve` | Approve an action request |
//! | `POST` | `/api/v1/action-requests/{id}/reject` | Reject an action request |
//! | `POST` | `/api/v1/action-requests/{id}/revoke` | Revoke an approved request |
//! | `POST` | `/api/v1/webhooks/github` | Receive GitHub webhook events (E-05) |
//!
//! # Idempotency
//!
//! The `propose`, `approve`, `reject`, and `revoke` endpoints honour the
//! `Idempotency-Key` header. When present, a second call with the same key
//! returns the original result without re-executing the mutation.
//!
//! # Webhook ingestion (E-05)
//!
//! The `/api/v1/webhooks/github` endpoint authenticates incoming GitHub
//! webhooks via HMAC-SHA256 signature validation, deduplicates by delivery
//! ID, records raw payload digests, and flags out-of-order events. See
//! [`webhook`] module for details.
//!
//! # OpenAPI
//!
//! The contract lives in `openapi/openapi.yaml` and is checked in CI.
//! The schema is derived from the request/response types in this crate.

pub mod error;
pub mod handlers;
pub mod models;
pub mod routes;
pub mod webhook;

pub use error::{ApiError, ErrorResponse};
pub use models::{
    ActionRequestResponse, ActionRequestSummary, ApproveRequest, CreateActionRequestRequest,
    RejectRequest, RevokeRequest,
};

use crate::error::{ErrorCause, ErrorDetail};
use axum::{extract::Request, middleware::Next, response::IntoResponse};
use piteka_application::ActionRequestUseCase;
use piteka_storage::{ActionRequestStore, ApprovalDecisionStore, AuditLog};

/// OpenAPI schema for the first-slice API (checked in at `openapi/openapi.yaml`).
///
/// The schema is maintained as a YAML file and regenerated by
/// `scripts/regenerate_openapi.sh` when source types change.
pub const OPENAPI_SPEC: &str = include_str!("../../../openapi/openapi.yaml");

/// Middleware that extracts tenant from the `X-Tenant-Id` header.
///
/// Fails closed when the header is missing.
#[allow(dead_code)]
async fn require_tenant(req: Request, next: Next) -> axum::response::Response {
    let tenant_id = req
        .headers()
        .get("X-Tenant-Id")
        .and_then(|v| v.to_str().ok())
        .map(|s| s.to_string());

    match tenant_id {
        Some(_id) => {
            let mut req = req;
            req.extensions_mut().insert(_id);
            next.run(req).await
        }
        None => (
            axum::http::StatusCode::BAD_REQUEST,
            axum::response::Json(ErrorResponse {
                error: ErrorDetail {
                    code: "MISSING_REQUIRED_HEADER".to_string(),
                    message: "The `X-Tenant-Id` header is required".to_string(),
                    causes: Some(vec![ErrorCause {
                        code: "MISSING_REQUIRED_HEADER".to_string(),
                        message: "The `X-Tenant-Id` header must be present".to_string(),
                        source: Some("X-Tenant-Id".to_string()),
                    }]),
                },
            }),
        )
            .into_response(),
    }
}

/// A minimal in-memory port implementation for testing.
#[derive(Clone)]
pub struct TestPorts {
    pub request_store: std::sync::Arc<piteka_storage::memory::InMemoryActionRequestStore>,
    pub decision_store: std::sync::Arc<piteka_storage::memory::InMemoryApprovalDecisionStore>,
    pub audit_log: std::sync::Arc<piteka_storage::memory::InMemoryAuditLog>,
    pub webhook_receipt_store: std::sync::Arc<piteka_storage::memory::InMemoryWebhookReceiptStore>,
    pub github_adapter: std::sync::Arc<MockGitHubAdapter>,
    pub webhook_processor: MockWebhookProcessor,
    // E-06: Receipt and evidence stores.
    pub receipt_store: std::sync::Arc<piteka_storage::memory::InMemoryReceiptProjectionStore>,
    pub evidence_store: std::sync::Arc<piteka_storage::memory::InMemoryEvidenceNodeStore>,
    pub evidence_blob_store: std::sync::Arc<piteka_storage::memory::InMemoryEvidenceStore>,
    pub protocol_store: std::sync::Arc<piteka_storage::memory::InMemoryProtocolObjectStore>,
    pub attempt_store: std::sync::Arc<piteka_storage::memory::InMemoryExecutionAttemptStore>,
    pub seal_consumption_store:
        std::sync::Arc<piteka_storage::memory::InMemorySealConsumptionStore>,
}

impl TestPorts {
    pub fn new() -> Self {
        Self {
            request_store: std::sync::Arc::new(
                piteka_storage::memory::InMemoryActionRequestStore::default(),
            ),
            decision_store: std::sync::Arc::new(
                piteka_storage::memory::InMemoryApprovalDecisionStore::default(),
            ),
            audit_log: std::sync::Arc::new(piteka_storage::memory::InMemoryAuditLog::default()),
            webhook_receipt_store: std::sync::Arc::new(
                piteka_storage::memory::InMemoryWebhookReceiptStore::default(),
            ),
            github_adapter: std::sync::Arc::new(MockGitHubAdapter::default()),
            webhook_processor: MockWebhookProcessor::default(),
            // E-06: Receipt and evidence stores.
            receipt_store: std::sync::Arc::new(
                piteka_storage::memory::InMemoryReceiptProjectionStore::default(),
            ),
            evidence_store: std::sync::Arc::new(
                piteka_storage::memory::InMemoryEvidenceNodeStore::default(),
            ),
            evidence_blob_store: std::sync::Arc::new(
                piteka_storage::memory::InMemoryEvidenceStore::default(),
            ),
            protocol_store: std::sync::Arc::new(
                piteka_storage::memory::InMemoryProtocolObjectStore::default(),
            ),
            attempt_store: std::sync::Arc::new(
                piteka_storage::memory::InMemoryExecutionAttemptStore::default(),
            ),
            seal_consumption_store: std::sync::Arc::new(
                piteka_storage::memory::InMemorySealConsumptionStore::default(),
            ),
        }
    }

    pub fn use_case(&self) -> ActionRequestUseCase<TestPorts> {
        ActionRequestUseCase::new(self.clone())
    }

    /// Returns a webhook ingestion use case configured with these test ports.
    pub fn webhook_ingestion(
        &self,
    ) -> piteka_application::WebhookIngestionUseCase<
        MockWebhookProcessor,
        std::sync::Arc<piteka_storage::memory::InMemoryWebhookReceiptStore>,
        std::sync::Arc<piteka_storage::memory::InMemoryAuditLog>,
    > {
        let ports = piteka_application::WebhookIngestionPorts::new(
            self.webhook_processor.clone(),
            self.webhook_receipt_store.clone(),
            self.audit_log.clone(),
        );
        piteka_application::WebhookIngestionUseCase::new(ports)
    }

    /// Returns HTTP state for the GitHub webhook endpoint.
    pub fn webhook_state(&self) -> webhook::WebhookStateConcrete {
        webhook::WebhookStateConcrete {
            ingestion: self.webhook_ingestion(),
            clock: piteka_application::SystemClock,
            github: self.github_adapter.clone(),
            webhook_secret: piteka_ports::github::GitHubWebhookSecret::new(
                "test-webhook-secret-reference",
            )
            .expect("static secret reference is non-empty"),
        }
    }
}

impl piteka_application::ActionRequestPorts for TestPorts {
    fn request_store(&self) -> &dyn ActionRequestStore {
        &self.request_store
    }

    fn decision_store(&self) -> &dyn ApprovalDecisionStore {
        &self.decision_store
    }

    fn audit_log(&self) -> &dyn AuditLog {
        &self.audit_log
    }

    fn clock(&self) -> &dyn piteka_application::Clock {
        // Return a static clock for testing purposes.
        // In production, this would return a reference to a real clock.
        static CLOCK: std::sync::OnceLock<TestClock> = std::sync::OnceLock::new();
        CLOCK.get_or_init(TestClock::default)
    }
}

impl Default for TestPorts {
    fn default() -> Self {
        Self::new()
    }
}

/// PostgreSQL-backed ports for the live action-request approval workflow.
///
/// The counterpart to [`TestPorts`] for real deployments: the propose →
/// approve/reject → revoke lifecycle is persisted to Postgres (the sole
/// live-state authority) instead of in-memory maps, so approvals survive
/// restarts and are visible to the read API and evidence feed. Each store is a
/// cheap clone over a shared connection pool.
#[derive(Clone)]
pub struct LiveActionRequestPorts {
    request_store: piteka_storage::postgres::PgActionRequestStore,
    decision_store: piteka_storage::postgres::PgApprovalDecisionStore,
    audit_log: piteka_storage::postgres::PgAuditLog,
    clock: piteka_application::SystemClock,
}

impl LiveActionRequestPorts {
    /// Connects a pool, runs migrations, and wires the live Postgres stores with
    /// a system clock. All three stores share the one pool.
    ///
    /// # Errors
    ///
    /// Returns a storage error if the pool cannot be established or migrations
    /// fail.
    pub async fn connect(database_url: &str) -> Result<Self, piteka_storage::StorageError> {
        let pool = piteka_storage::postgres::connect(database_url).await?;
        piteka_storage::postgres::run_migrations(&pool).await?;
        Ok(Self {
            request_store: piteka_storage::postgres::PgActionRequestStore::new(pool.clone()),
            decision_store: piteka_storage::postgres::PgApprovalDecisionStore::new(pool.clone()),
            audit_log: piteka_storage::postgres::PgAuditLog::new(pool),
            clock: piteka_application::SystemClock,
        })
    }

    /// Returns an action-request use case configured with these live ports.
    #[must_use]
    pub fn use_case(&self) -> ActionRequestUseCase<LiveActionRequestPorts> {
        ActionRequestUseCase::new(self.clone())
    }
}

impl piteka_application::ActionRequestPorts for LiveActionRequestPorts {
    fn request_store(&self) -> &dyn ActionRequestStore {
        &self.request_store
    }

    fn decision_store(&self) -> &dyn ApprovalDecisionStore {
        &self.decision_store
    }

    fn audit_log(&self) -> &dyn AuditLog {
        &self.audit_log
    }

    fn clock(&self) -> &dyn piteka_application::Clock {
        &self.clock
    }
}

/// A deterministic clock that steps forward by 1 second per call.
#[derive(Default)]
struct TestClock {
    now: std::sync::Arc<std::sync::atomic::AtomicU64>,
}

impl TestClock {
    #[allow(dead_code)]
    fn at(second: u64) -> Self {
        Self {
            now: std::sync::Arc::new(std::sync::atomic::AtomicU64::new(second)),
        }
    }
}

impl piteka_application::Clock for TestClock {
    fn unix_seconds(&self) -> u64 {
        self.now.fetch_add(1, std::sync::atomic::Ordering::SeqCst)
    }
}

/// A mock GitHub adapter for testing webhook signature verification.
#[derive(Clone)]
pub struct MockGitHubAdapter {
    pub verify_result:
        std::sync::Arc<std::sync::Mutex<Option<piteka_ports::github::WebhookSignatureResult>>>,
}

impl Default for MockGitHubAdapter {
    fn default() -> Self {
        Self {
            // Fail closed unless a test explicitly enables authentication.
            verify_result: std::sync::Arc::new(std::sync::Mutex::new(Some(
                piteka_ports::github::WebhookSignatureResult::Invalid,
            ))),
        }
    }
}

#[async_trait::async_trait]
impl piteka_application::WebhookEventProcessor for MockWebhookProcessor {
    async fn process(
        &self,
        event_type: &str,
        payload: &[u8],
        delivery_id: &str,
        out_of_order: bool,
    ) -> piteka_application::webhook_ingestion::error::WebhookResult<()> {
        let mut recorded = self.recorded.lock().expect("lock poisoned");
        recorded.push(WebhookEventRecord {
            event_type: event_type.to_string(),
            delivery_id: delivery_id.to_string(),
            payload_length: payload.len(),
            out_of_order,
        });
        Ok(())
    }
}

/// A record of a processed webhook event.
#[derive(Clone, Debug)]
pub struct WebhookEventRecord {
    pub event_type: String,
    pub delivery_id: String,
    pub payload_length: usize,
    pub out_of_order: bool,
}

/// A mock webhook event processor for testing.
#[derive(Clone, Default)]
pub struct MockWebhookProcessor {
    pub recorded: std::sync::Arc<std::sync::Mutex<Vec<WebhookEventRecord>>>,
}

/// A mock GitHub adapter for testing webhook signature verification.
#[async_trait::async_trait]
impl piteka_ports::github::GitHubAppPort for MockGitHubAdapter {
    async fn verify_webhook_signature(
        &self,
        _payload: &piteka_ports::github::GitHubWebhookPayload,
        _webhook_secret: &piteka_ports::github::GitHubWebhookSecret,
    ) -> Result<piteka_ports::github::WebhookSignatureResult, piteka_ports::github::GitHubAppError>
    {
        if let Ok(secret) = std::env::var("PITEKA_GITHUB_WEBHOOK_SECRET") {
            if secret.is_empty() {
                return Ok(piteka_ports::github::WebhookSignatureResult::Invalid);
            }
            return Ok(piteka_github::verify_webhook_signature_internal(
                &_payload.body,
                &_payload.signature,
                &secret,
            ));
        }
        let guard = self.verify_result.lock().expect("lock poisoned");
        Ok(guard.unwrap_or(piteka_ports::github::WebhookSignatureResult::Invalid))
    }

    async fn create_deployment(
        &self,
        _installation_id: &piteka_ports::github::GitHubInstallationId,
        _repository_id: &piteka_ports::github::GitHubRepositoryId,
        _commit_sha: &str,
        _environment: &piteka_ports::github::GitHubEnvironmentName,
        _auto_merge: bool,
        _payload_commitment: &str,
        _attempt_digest: [u8; 32],
    ) -> Result<piteka_ports::github::DeploymentCreated, piteka_ports::github::GitHubAppError> {
        Ok(piteka_ports::github::DeploymentCreated {
            deployment_id: 0,
            url: String::new(),
            attempt_digest: [0u8; 32],
        })
    }

    fn installation_context(&self) -> piteka_ports::github::GitHubInstallationContext {
        piteka_ports::github::GitHubInstallationContext {
            installation_id: piteka_ports::github::GitHubInstallationId::new("1").unwrap(),
            repository_id: piteka_ports::github::GitHubRepositoryId::new("1").unwrap(),
            repository_name: piteka_ports::github::GitHubRepositoryName::new("demo/demo").unwrap(),
            environment_id: piteka_ports::github::GitHubEnvironmentId::new("1").unwrap(),
            environment_name: piteka_ports::github::GitHubEnvironmentName::new("production")
                .unwrap(),
        }
    }

    fn serving_organization(&self) -> &piteka_domain::OrganizationId {
        static ORG: std::sync::OnceLock<piteka_domain::OrganizationId> = std::sync::OnceLock::new();
        ORG.get_or_init(|| piteka_domain::OrganizationId::new("demo-org").unwrap())
    }
}

#[cfg(test)]
mod tests;
