[package]
name = "piteka-worker"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
piteka-application.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints.rust]
unsafe_code = "forbid"
